export const categories = [
  {
    id: 1,
    name: 'Italian',
    description: 'Classic Italian dishes with rich flavors',
    image: require('../assets/italian.jpg'),
  },
  {
    id: 2,
    name: 'Mexican',
    description: 'Spicy and vibrant Mexican cuisine',
    image: require('../assets/mexican.jpg'),
  },
  {
    id: 3,
    name: 'Japanese',
    description: 'Delicate and balanced Japanese flavors',
    image: require('../assets/japanese.jpg'),
  },
  {
    id: 4,
    name: 'Chinese',
    description: 'Diverse and flavorful Chinese dishes',
    image: require('../assets/chinese.jpg'),
  },
  {
    id: 5,
    name: 'Pakistani',
    description: 'Aromatic and hearty Pakistani meals',
    image: require('../assets/pakistani.jpg'),
  },
 
];

export const recipes = {
  italian: [
    {
      id: 1,
      name: 'Spaghetti Aglio e Olio',
      category: 'Italian',
      image: require('../assets/spaghetti.jpg'),
      time: '15-20 mins',
      difficulty: 'Easy',
      rating: 4.5,
      ingredients: [
        '12 oz spaghetti',
        '3 cloves garlic, minced',
        '1/3 cup olive oil',
        '4-6 red pepper flakes',
        'Salt and pepper',
        'Grated Parmesan cheese (optional)',
      ],
      steps: [
        'Cook spaghetti in boiling salted water until al dente. Reserve 1 cup pasta water before draining.',
        'In a large skillet, heat olive oil over medium heat. Add garlic and cook until golden, about 2-3 minutes.',
        'Add red pepper flakes and cook for another minute.',
        'Add reserved pasta water to the skillet and toss with cooked spaghetti.',
        'Season with salt and pepper to taste. Serve with Parmesan cheese if desired.',
      ],
      nutrition: {
        calories: 450,
        protein: '12g',
        carbs: '60g',
        fat: '18g',
      },
      allergens: ['Gluten'],
    },
    // ... other Italian recipes
     {
      id: 2,
      name: 'Bruschetta',
      category: 'Italian',
      image: require('../assets/bruschetta.jpg'),
      time: '10-12 mins',
      difficulty: 'Easy',
      rating: 4.3,
      ingredients: [
        '4-6 baguette slices',
        '1 large tomato, diced',
        '1/4 cup fresh basil, chopped',
        '2 cloves garlic, minced',
        '2 tbsp olive oil',
        'Salt and pepper',
        '1/4 cup mozzarella cheese (optional)',
      ],
      steps: [
        'Preheat oven to 400°F (200°C).',
        'Toast baguette slices in the oven for 2-3 minutes per side.',
        'Mix diced tomato, chopped basil, garlic, salt, and pepper.',
        'Brush toasted bread with olive oil and top with tomato mixture and mozzarella cheese if using.',
      ],
      nutrition: {
        calories: 180,
        protein: '5g',
        carbs: '22g',
        fat: '8g',
      },
      allergens: ['Gluten'],
    },
    {
      id: 3,
      name: 'Caprese Salad',
      category: 'Italian',
      image: require('../assets/caprese.jpg'),
      time: '10 mins',
      difficulty: 'Easy',
      rating: 4.2,
      ingredients: [
        '2 large tomatoes, sliced',
        '8 oz fresh mozzarella cheese, sliced',
        '1/4 cup fresh basil leaves, chopped',
        '2 tbsp olive oil',
        'Salt and pepper',
      ],
      steps: [
        'Arrange tomato and mozzarella slices on a plate.',
        'Drizzle with olive oil and sprinkle with chopped basil.',
        'Season with salt and pepper to taste.',
      ],
      nutrition: {
        calories: 250,
        protein: '14g',
        carbs: '6g',
        fat: '20g',
      },
      allergens: ['Dairy'],
    },
    {
      id: 4,
      name: 'Garlic Bread',
      category: 'Italian',
      image: require('../assets/garlic-bread.jpg'),
      time: '12-15 mins',
      difficulty: 'Easy',
      rating: 4.0,
      ingredients: [
        '1 baguette',
        '3 cloves garlic, minced',
        '1/2 cup butter, softened',
        'Salt and pepper',
      ],
      steps: [
        'Preheat oven to 350°F (175°C).',
        'Mix minced garlic and softened butter.',
        'Slice baguette and spread garlic butter on each slice.',
        'Bake for 10-12 minutes or until golden brown.',
      ],
      nutrition: {
        calories: 220,
        protein: '4g',
        carbs: '24g',
        fat: '12g',
      },
      allergens: ['Gluten', 'Dairy'],
    },
    {
      id: 5,
      name: 'Lasagna',
      category: 'Italian',
      image: require('../assets/lasagna.jpg'),
      time: '45-60 mins',
      difficulty: 'Medium',
      rating: 4.8,
      ingredients: [
        '8 lasagna noodles',
        '1 pound ground beef',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '2 cups marinara sauce',
        '1 cup ricotta cheese',
        '1 cup shredded mozzarella cheese',
      ],
      steps: [
        'Preheat oven to 375°F (190°C).',
        'Cook lasagna noodles according to package instructions.',
        'Brown ground beef with diced onion and garlic. Add marinara sauce.',
        'Layer lasagna noodles, meat sauce, ricotta cheese, and mozzarella cheese in a baking dish.',
        'Bake for 30-40 minutes or until golden brown.',
      ],
      nutrition: {
        calories: 520,
        protein: '32g',
        carbs: '42g',
        fat: '26g',
      },
      allergens: ['Gluten', 'Dairy'],
    }
  ],
  mexican: [
    {
      id: 6,
      name: 'Tacos',
      category: 'Mexican',
      image: require('../assets/tacos.jpg'),
      time: '20-30 mins',
      difficulty: 'Easy',
      rating: 4.7,
      ingredients: [
        '1 pound ground beef or chicken',
        '1/2 medium onion, diced',
        '1 packet taco seasoning',
        '8-10 taco shells',
        'Shredded lettuce',
        'Diced tomatoes',
        'Shredded cheese',
        'Salsa',
      ],
      steps: [
        'Cook ground beef or chicken in a pan over medium heat. Add diced onion and taco seasoning. Simmer until meat is cooked through.',
        'Warm taco shells according to package instructions.',
        'Fill taco shells with meat mixture, shredded lettuce, diced tomatoes, and shredded cheese.',
        'Serve with salsa.',
      ],
      nutrition: {
        calories: 350,
        protein: '20g',
        carbs: '25g',
        fat: '18g',
      },
      allergens: ['Gluten', 'Dairy'],
    },
    // ... other Mexican recipes
    {
      id: 7,
      name: 'Quesadillas',
      category: 'Mexican',
      image: require('../assets/quesadilla.jpg'),
      time: '15-20 mins',
      difficulty: 'Easy',
      rating: 4.5,
      ingredients: [
        '4 large tortillas',
        '2 cups shredded cheese',
        '1 cup cooked chicken or beef, shredded',
        '1/4 cup chopped onion',
        '1/4 cup chopped bell pepper',
      ],
      steps: [
        'Heat a large skillet over medium heat.',
        'Place a tortilla in the skillet and sprinkle with cheese, chicken or beef, onion, and bell pepper.',
        'Fold tortilla in half and cook until cheese is melted and tortilla is crispy.',
        'Flip quesadilla and cook the other side until crispy.',
      ],
      nutrition: {
        calories: 420,
        protein: '25g',
        carbs: '28g',
        fat: '22g',
      },
      allergens: ['Gluten', 'Dairy'],
    },
    {
      id: 8,
      name: 'Enchiladas',
      category: 'Mexican',
      image: require('../assets/enchiladas.jpg'),
      time: '40-50 mins',
      difficulty: 'Medium',
      rating: 4.6,
      ingredients: [
        '8-10 tortillas',
        '1 pound ground beef or chicken',
        '1 can enchilada sauce',
        '1 cup shredded cheese',
        '1/4 cup chopped onion',
      ],
      steps: [
        'Preheat oven to 375°F (190°C).',
        'Cook ground beef or chicken in a pan over medium heat. Add chopped onion and cook until tender.',
        'Dip tortillas in enchilada sauce and fill with meat mixture and shredded cheese.',
        'Roll up tortillas and place in a baking dish. Pour enchilada sauce over top and sprinkle with cheese.',
        'Bake for 20-25 minutes or until cheese is melted and bubbly.',
      ],
      nutrition: {
        calories: 380,
        protein: '22g',
        carbs: '30g',
        fat: '20g',
      },
      allergens: ['Gluten', 'Dairy'],
    },
    {
      id: 9,
      name: 'Chiles Rellenos',
      category: 'Mexican',
      image: require('../assets/chiles-rellenos.jpg'),
      time: '30-40 mins',
      difficulty: 'Medium',
      rating: 4.4,
      ingredients: [
        '4 poblano peppers',
        '1 pound queso fresco or Monterey Jack cheese',
        '1/4 cup chopped onion',
        '1/4 cup chopped cilantro',
      ],
      steps: [
        'Roast poblano peppers over an open flame or in the oven until charred.',
        'Peel peppers and remove seeds.',
        'Stuff peppers with cheese, onion, and cilantro.',
        'Coat peppers with an egg batter and fry until golden brown.',
      ],
      nutrition: {
        calories: 320,
        protein: '18g',
        carbs: '12g',
        fat: '22g',
      },
      allergens: ['Dairy', 'Eggs'],
    },
    {
      id: 10,
      name: 'Guacamole',
      category: 'Mexican',
      image: require('../assets/guacamole.jpg'),
      time: '10-15 mins',
      difficulty: 'Easy',
      rating: 4.8,
      ingredients: [
        '3 ripe avocados',
        '1 lime, juiced',
        '1/2 medium onion, diced',
        '1 jalapeño pepper, seeded and finely chopped',
        'Salt, to taste',
      ],
      steps: [
        'Cut avocados in half and remove pit.',
        'Mash avocados in a bowl with a fork.',
        'Add lime juice, diced onion, and chopped jalapeño to bowl. Mix well.',
        'Season with salt to taste.',
      ],
      nutrition: {
        calories: 160,
        protein: '2g',
        carbs: '9g',
        fat: '15g',
      },
      allergens: [],
    }
  ],
  japanese: [
    {
      id: 11,
      name: 'Sushi',
      category: 'Japanese',
      image: require('../assets/sushi.jpg'),
      time: '30-40 mins',
      difficulty: 'Medium',
      rating: 4.9,
      ingredients: [
        'Short-grain Japanese rice',
        'Nori (seaweed sheets)',
        'Various fillings (e.g., raw fish, avocado, cucumber)',
      ],
      steps: [
        'Prepare sushi rice according to package instructions.',
        'Lay nori sheet flat and spread sushi rice evenly.',
        'Add desired fillings in the middle of the rice.',
        'Roll sushi using a bamboo mat.',
      ],
      nutrition: {
        calories: 200,
        protein: '6g',
        carbs: '38g',
        fat: '1g',
      },
      allergens: ['Fish', 'Shellfish'],
    },
    // ... other Japanese recipes
     {
      id: 12,
      name: 'Ramen',
      category: 'Japanese',
      image: require('../assets/ramen.jpg'),
      time: '40-60 mins',
      difficulty: 'Medium',
      rating: 4.7,
      ingredients: [
        'Ramen noodles',
        'Pork or chicken broth',
        'Vegetables (e.g., green onions, bean sprouts)',
        'Protein (e.g., pork slices, boiled egg)',
      ],
      steps: [
        'Cook ramen noodles according to package instructions.',
        'Prepare broth by simmering pork or chicken bones in water.',
        'Add vegetables and protein to the broth.',
        'Serve noodles in the hot broth.',
      ],
      nutrition: {
        calories: 450,
        protein: '20g',
        carbs: '50g',
        fat: '18g',
      },
      allergens: ['Gluten', 'Eggs'],
    },
    {
      id: 13,
      name: 'Tempura',
      category: 'Japanese',
      image: require('../assets/tempura.jpg'),
      time: '20-30 mins',
      difficulty: 'Medium',
      rating: 4.5,
      ingredients: [
        'Seafood or vegetables (e.g., shrimp, carrots)',
        'Tempura batter mix',
        'Vegetable oil for frying',
      ],
      steps: [
        'Prepare tempura batter according to package instructions.',
        'Dip seafood or vegetables in the batter.',
        'Fry in hot oil until golden brown.',
        'Drain excess oil on paper towels.',
      ],
      nutrition: {
        calories: 280,
        protein: '8g',
        carbs: '22g',
        fat: '18g',
      },
      allergens: ['Gluten', 'Shellfish'],
    },
    {
      id: 14,
      name: 'Yakitori',
      category: 'Japanese',
      image: require('../assets/yakitori.jpg'),
      time: '15-25 mins',
      difficulty: 'Easy',
      rating: 4.4,
      ingredients: [
        'Chicken pieces (e.g., thighs, breast)',
        'Yakitori sauce (e.g., soy sauce, sake, mirin)',
        'Skewers',
      ],
      steps: [
        'Thread chicken pieces onto skewers.',
        'Grill or broil skewers until cooked through.',
        'Brush with yakitori sauce during cooking.',
        'Serve hot.',
      ],
      nutrition: {
        calories: 220,
        protein: '25g',
        carbs: '5g',
        fat: '10g',
      },
      allergens: ['Soy'],
    },
    {
      id: 15,
      name: 'Udon Noodles',
      category: 'Japanese',
      image: require('../assets/udon.jpg'),
      time: '15-30 mins',
      difficulty: 'Easy',
      rating: 4.3,
      ingredients: [
        'Udon noodles',
        'Hot broth (e.g., dashi, soy sauce)',
        'Vegetables (e.g., green onions, tempura bits)',
      ],
      steps: [
        'Cook udon noodles according to package instructions.',
        'Prepare hot broth by simmering dashi ingredients.',
        'Serve noodles in the hot broth with desired toppings.',
      ],
      nutrition: {
        calories: 350,
        protein: '12g',
        carbs: '65g',
        fat: '5g',
      },
      allergens: ['Gluten', 'Soy'],
    }
  ],
  chinese: [
    {
      id: 16,
      name: 'Kung Pao Chicken',
      category: 'Chinese',
      image: require('../assets/kung-pao.jpg'),
      time: '20 mins',
      difficulty: 'Medium',
      rating: 4.6,
      ingredients: [
        '1 pound boneless skinless chicken breasts, cut into bite-sized pieces',
        '2 tablespoons vegetable oil',
        '3 cloves garlic, minced',
        '1 tablespoon ginger, minced',
        '1 cup peanuts or cashews',
        '1 cup vegetables (bell peppers, carrots, scallions)',
        '2 teaspoons soy sauce',
        '1 teaspoon Shaoxing wine',
        '1 tablespoon cornstarch',
      ],
      steps: [
        'Heat oil in a wok over medium-high heat. Add chicken and cook until browned.',
        'Add garlic, ginger, and peanuts. Stir-fry for 1 minute.',
        'Add vegetables and stir-fry until tender-crisp.',
        'Mix soy sauce, Shaoxing wine, and cornstarch. Pour the sauce into the wok and stir-fry until thickened.',
      ],
      nutrition: {
        calories: 380,
        protein: '30g',
        carbs: '15g',
        fat: '22g',
      },
      allergens: ['Peanuts', 'Soy'],
    },
    // ... other Chinese recipes
     {
      id: 17,
      name: 'Fried Rice',
      category: 'Chinese',
      image: require('../assets/fried-rice.jpg'),
      time: '15-20 mins',
      difficulty: 'Easy',
      rating: 4.5,
      ingredients: [
        '2 cups cooked rice (preferably day-old)',
        '1 tablespoon vegetable oil',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '1 cup mixed vegetables (peas, carrots, corn)',
        '2 eggs, beaten',
        '2 teaspoons soy sauce',
      ],
      steps: [
        'Heat oil in a wok over medium-high heat. Add onion and garlic and stir-fry until softened.',
        'Add mixed vegetables and cooked rice. Stir-fry until combined.',
        'Push rice mixture aside. Add more oil if needed, then pour in eggs. Scramble eggs until cooked through.',
        'Mix eggs with rice mixture. Add soy sauce and stir-fry until combined.',
      ],
      nutrition: {
        calories: 320,
        protein: '10g',
        carbs: '45g',
        fat: '10g',
      },
      allergens: ['Eggs', 'Soy'],
    },
    {
      id: 18,
      name: 'Dumplings',
      category: 'Chinese',
      image: require('../assets/dumplings.jpg'),
      time: '30-40 mins',
      difficulty: 'Medium',
      rating: 4.7,
      ingredients: [
        '2 cups all-purpose flour',
        '2 tablespoons salt',
        '1/4 cup warm water',
        'Filling ingredients (ground pork, cabbage, ginger, garlic, soy sauce)',
      ],
      steps: [
        'Mix flour and salt in a bowl. Gradually add warm water and knead until dough forms.',
        'Divide dough into small balls. Roll out each ball into a thin wrapper.',
        'Place a spoonful of filling in the center of each wrapper. Fold and press edges to seal.',
        'Steam or pan-fry dumplings until cooked through.',
      ],
      nutrition: {
        calories: 280,
        protein: '12g',
        carbs: '35g',
        fat: '10g',
      },
      allergens: ['Gluten', 'Soy'],
    },
    {
      id: 19,
      name: 'Egg Foo Young',
      category: 'Chinese',
      image: require('../assets/egg-foo-young.jpg'),
      time: '15-20 mins',
      difficulty: 'Easy',
      rating: 4.3,
      ingredients: [
        '2 eggs',
        '1 cup mixed vegetables (bean sprouts, cabbage, scallions)',
        '1 cup cooked chicken or shrimp, diced',
        '2 tablespoons soy sauce',
        '2 tablespoons vegetable oil',
      ],
      steps: [
        'Beat eggs in a bowl. Add mixed vegetables, cooked chicken or shrimp, and soy sauce. Mix well.',
        'Heat oil in a non-stick skillet over medium heat. Pour in egg mixture.',
        'Cook until eggs are set, then flip and cook the other side.',
      ],
      nutrition: {
        calories: 220,
        protein: '18g',
        carbs: '8g',
        fat: '14g',
      },
      allergens: ['Eggs', 'Shellfish', 'Soy'],
    },
    {
      id: 20,
      name: 'Orange Chicken',
      category: 'Chinese',
      image: require('../assets/orange-chicken.jpg'),
      time: '30 mins',
      difficulty: 'Medium',
      rating: 4.8,
      ingredients: [
        '1 pound boneless skinless chicken thighs',
        '1 cup all-purpose flour',
        '1/2 cup cornstarch',
        'Vegetable oil for frying',
        '1 orange, juiced',
        '2 tablespoons soy sauce',
        '1 tablespoon brown sugar',
      ],
      steps: [
        'Cut chicken into bite-sized pieces. Mix flour and cornstarch in a bowl. Add chicken and coat evenly.',
        'Fry chicken in hot oil until golden brown. Drain excess oil.',
        'Mix orange juice, soy sauce, and brown sugar in a saucepan. Bring to a boil, then add fried chicken.',
        'Toss chicken in sauce until coated.',
      ],
      nutrition: {
        calories: 420,
        protein: '28g',
        carbs: '45g',
        fat: '16g',
      },
      allergens: ['Gluten', 'Soy'],
    }
  ],
  pakistani: [
    {
      id: 21,
      name: 'Biryani',
      category: 'Pakistani',
      image: require('../assets/biryani.jpg'),
      time: '60-90 mins',
      difficulty: 'Hard',
      rating: 4.9,
      ingredients: [
        '1 cup basmati rice',
        '1 pound lamb or beef, cut into small pieces',
        '1 onion, chopped',
        '2 cloves garlic, minced',
        '1 tablespoon ginger paste',
        '1 teaspoon cumin powder',
        '1 teaspoon coriander powder',
        'Salt, to taste',
        '2 tablespoons ghee or oil',
      ],
      steps: [
        'Cook rice and set aside.',
        'Heat oil in a pan over medium heat. Add onions and cook until golden brown.',
        'Add ginger paste and garlic. Cook for 1 minute.',
        'Add lamb or beef pieces. Cook until browned.',
        'Layer cooked rice and meat mixture in a pot. Steam for 10-15 minutes.',
      ],
      nutrition: {
        calories: 550,
        protein: '30g',
        carbs: '60g',
        fat: '22g',
      },
      allergens: [],
    },
    // ... other Pakistani recipes
     {
      id: 22,
      name: 'Kebabs',
      category: 'Pakistani',
      image: require('../assets/kebabs.jpg'),
      time: '20-30 mins',
      difficulty: 'Medium',
      rating: 4.7,
      ingredients: [
        '1 pound lamb or beef, minced',
        '1 onion, finely chopped',
        '2 cloves garlic, minced',
        '1 tablespoon ginger paste',
        '1 teaspoon cumin powder',
        '1 teaspoon coriander powder',
        'Salt, to taste',
      ],
      steps: [
        'Mix minced meat, onion, garlic, ginger paste, cumin powder, coriander powder, and salt.',
        'Shape into skewers.',
        'Grill or pan-fry kebabs until cooked through.',
      ],
      nutrition: {
        calories: 320,
        protein: '28g',
        carbs: '5g',
        fat: '22g',
      },
      allergens: [],
    },
    {
      id: 23,
      name: 'Haleem',
      category: 'Pakistani',
      image: require('../assets/haleem.jpg'),
      time: '60-90 mins',
      difficulty: 'Hard',
      rating: 4.8,
      ingredients: [
        '1 pound lamb or beef, cut into small pieces',
        '1 cup wheat or barley',
        '2 medium onions, chopped',
        '2 cloves garlic, minced',
        '1 tablespoon ginger paste',
        '1 teaspoon cumin powder',
        '1 teaspoon coriander powder',
        'Salt, to taste',
      ],
      steps: [
        'Cook wheat or barley and set aside.',
        'Heat oil in a pan over medium heat. Add onions and cook until golden brown.',
        'Add ginger paste and garlic. Cook for 1 minute.',
        'Add lamb or beef pieces. Cook until browned.',
        'Mix cooked wheat or barley with meat mixture. Simmer for 10-15 minutes.',
      ],
      nutrition: {
        calories: 480,
        protein: '32g',
        carbs: '45g',
        fat: '20g',
      },
      allergens: ['Gluten'],
    },
    {
      id: 24,
      name: 'Nihari',
      category: 'Pakistani',
      image: require('../assets/nihari.jpg'),
      time: '120-150 mins',
      difficulty: 'Hard',
      rating: 4.9,
      ingredients: [
        '1 pound lamb or beef, cut into small pieces',
        '2 medium onions, chopped',
        '2 cloves garlic, minced',
        '1 tablespoon ginger paste',
        '1 teaspoon cumin powder',
        '1 teaspoon coriander powder',
        'Salt, to taste',
        '2 tablespoons nihari masala',
      ],
      steps: [
        'Heat oil in a pan over medium heat. Add onions and cook until golden brown.',
        'Add ginger paste and garlic. Cook for 1 minute.',
        'Add lamb or beef pieces. Cook until browned.',
        'Add nihari masala and simmer for 1-2 hours or until meat is tender.',
      ],
      nutrition: {
        calories: 520,
        protein: '35g',
        carbs: '15g',
        fat: '35g',
      },
      allergens: [],
    },
    {
      id: 25,
      name: 'Karahi',
      category: 'Pakistani',
      image: require('../assets/karahi.jpg'),
      time: '30-40 mins',
      difficulty: 'Medium',
      rating: 4.7,
      ingredients: [
        '1 pound lamb or beef, cut into small pieces',
        '2 medium onions, chopped',
        '2 cloves garlic, minced',
        '1 tablespoon ginger paste',
        '1 teaspoon cumin powder',
        '1 teaspoon coriander powder',
        'Salt, to taste',
        '2-3 green chilies, chopped',
      ],
      steps: [
        'Heat oil in a wok over medium heat. Add onions and cook until golden brown.',
        'Add ginger paste and garlic. Cook for 1 minute.',
        'Add lamb or beef pieces. Cook until browned.',
        'Add cumin powder, coriander powder, and salt. Mix well.',
        'Add green chilies and simmer for 10-15 minutes or until meat is tender.',
      ],
      nutrition: {
        calories: 380,
        protein: '30g',
        carbs: '10g',
        fat: '25g',
      },
      allergens: [],
    }
  ]
  
};

export const users = [
  {
    id: 1,
    email: 'user@example.com',
    password: 'password123'
  }
];